// block4_4_32.comp
// File version follows on next line.
11

// Number of components
3

// Component 0 follows.
block4_4_32_1.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 1 follows.
block4_4_32_2.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 2 follows.
block4_4_32_3.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

