// File version
11

// Number of components
4

// Component 0 follows.
brid128_64_64_1.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 1 follows.
brid128_64_64_2.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 2 follows.
brid128_64_64_4.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 3 follows.
brid128_64_64_3.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

