// cube32-blocker.comp
// File version follows on next line.
11

// Number of components
3

// Component 0 follows.
cube32_1-blocker.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 1 follows.
cube32_2-blocker.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 2 follows.
cube32_3-blocker.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

