// cube8.comp
// File version follows on next line.
11

// Number of components
3

// Component 0 follows.
cube8_1.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 1 follows.
cube8_2.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 2 follows.
cube8_3.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

