// heart-golf2.comp
// File version follows on next line.
11

// Number of components
3

// Component 0 follows.
heart-g.comp
// Translation x, y, z
-2
4
0
// Rotation x, y, z
0
0
225

// Component 1 follows.
heart-l.comp
// Translation x, y, z
0
4
0
// Rotation x, y, z
0
0
225

// Component 2 follows.
heart-f.comp
// Translation x, y, z
8
-1
0
// Rotation x, y, z
0
0
225

