// hole-block-b128_4_128.comp
// File version follows on next line.
11

// Number of components
3

// Component 0 follows.
block-hole-128_4_128-2_1.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 1 follows.
block-hole-128_4_128-2_2.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 2 follows.
block-hole-128_4_128-2_3.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

