// level-1-room-9.comp
// File version follows on next line.
11

// Number of components
4

// Component 0 follows.
cube32.comp
// Translation x, y, z
49
0
-80
// Rotation x, y, z
0
0
0

// Component 1 follows.
cube32.comp
// Translation x, y, z
-47
0
-80
// Rotation x, y, z
0
0
0

// Component 2 follows.
cube32.comp
// Translation x, y, z
-47
0
16
// Rotation x, y, z
0
0
0

// Component 3 follows.
cube32.comp
// Translation x, y, z
49
0
16
// Rotation x, y, z
0
0
0

