// ramp32_64-2.comp
// File version follows on next line.
11

// Number of components
3

// Component 0 follows.
ramp32_1_64-2.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 1 follows.
ramp32_2_64-2.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 2 follows.
ramp32_3_64-2.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

