// File version
11

// Number of components
25

// Component 0 follows.
table2.comp
// Translation x, y, z
0
0
0.179295
// Rotation x, y, z
0
0
0

// Component 1 follows.
table2.comp
// Translation x, y, z
-0.0246563
0
-0.151525
// Rotation x, y, z
0
180
0

// Component 2 follows.
table3.comp
// Translation x, y, z
0.101563
0
0.125304
// Rotation x, y, z
0
0
0

// Component 3 follows.
table3.comp
// Translation x, y, z
-0.110236
0
-0.126061
// Rotation x, y, z
0
180
0

// Component 4 follows.
table3.comp
// Translation x, y, z
0.0832939
0
-22.6176
// Rotation x, y, z
0
0
0

// Component 5 follows.
table3.comp
// Translation x, y, z
-0.126219
0
22.5499
// Rotation x, y, z
0
180
0

// Component 6 follows.
table6.comp
// Translation x, y, z
-0.609674
-0.49262
-1.08473
// Rotation x, y, z
0
0
0

// Component 7 follows.
table6.comp
// Translation x, y, z
0.61587
-0.508918
1.08188
// Rotation x, y, z
0
180
0

// Component 8 follows.
table6.comp
// Translation x, y, z
-10.1878
-0.473902
-8.5025
// Rotation x, y, z
0
90
0

// Component 9 follows.
table6.comp
// Translation x, y, z
10.1392
-0.478981
8.48157
// Rotation x, y, z
0
270
0

// Component 10 follows.
table7.comp
// Translation x, y, z
-0.669507
-0.50951
-0.0275411
// Rotation x, y, z
0
0
0

// Component 11 follows.
table7.comp
// Translation x, y, z
0.660986
-0.50951
0.0137705
// Rotation x, y, z
0
180
0

// Component 12 follows.
table8.leaf
// Translation x, y, z
0
1
0
// Rotation x, y, z
0
0
0

// Component 13 follows.
table9.leaf
// Translation x, y, z
-8.67392
-4.77471
-15.9589
// Rotation x, y, z
0
0
0

// Component 14 follows.
table9.leaf
// Translation x, y, z
-8.6006
-4.83534
16.3545
// Rotation x, y, z
0
0
0

// Component 15 follows.
table9.leaf
// Translation x, y, z
8.6159
-4.66549
16.3545
// Rotation x, y, z
0
0
0

// Component 16 follows.
table9.leaf
// Translation x, y, z
8.7478
-4.73839
-15.9589
// Rotation x, y, z
0
0
0

// Component 17 follows.
table11.leaf
// Translation x, y, z
-0.193824
10.5381
8.99911
// Rotation x, y, z
0
0
0

// Component 18 follows.
baize2.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 19 follows.
TABLE-R1.leaf
// Translation x, y, z
6.72296
0
22.5175
// Rotation x, y, z
0
0
0

// Component 20 follows.
TABLE-R1.leaf
// Translation x, y, z
-6.75277
0
-22.601
// Rotation x, y, z
0
180
0

// Component 21 follows.
table-r2.leaf
// Translation x, y, z
13.4344
0
5.71568
// Rotation x, y, z
0
0
0

// Component 22 follows.
table-r2.leaf
// Translation x, y, z
13.4128
0
-16.8171
// Rotation x, y, z
0
0
0

// Component 23 follows.
table-r2.leaf
// Translation x, y, z
-13.4938
0
-5.74166
// Rotation x, y, z
0
180
0

// Component 24 follows.
table-r2.leaf
// Translation x, y, z
-13.3819
0
16.7713
// Rotation x, y, z
0
180
0

