// threeq.comp
// File version follows on next line.
11

// Number of components
3

// Component 0 follows.
quarter32_4_32.comp
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 1 follows.
quarter32_4_32.comp
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
270
0

// Component 2 follows.
quarter32_4_32.comp
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
-180
0

