// File version
11

// Number of components
3

// Component 1 follows.
table-crazy.comp
// Translation x, y, z
0
-10
0
// Rotation x, y, z
0
0
0

// Component 0 follows.
pool-room.comp
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 2 follows.
oct12.comp
// Translation x, y, z
0
3.68719
-12
// Rotation x, y, z
0
0
0

shadow-table1.leaf
// Translation x, y, z
0
-9.5
0
// Rotation x, y, z
0
0
0

