// block32_4_16.comp
// File version follows on next line.
11

// Number of components
3

// Component 0 follows.
block32_4_16_1.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 1 follows.
block32_4_16_2.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 2 follows.
block32_4_16_3.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

