// heart-p.comp
// File version follows on next line.
11

// Number of components
3

// Component 0 follows.
heart-p1.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 1 follows.
heart-p2.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 2 follows.
heart-p3.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

