// hole-block_a128_4_128.comp
// File version follows on next line.
11

// Number of components
3

// Component 0 follows.
hole-block_a128_4_128-1_1.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 1 follows.
hole-block_a128_4_128-1_2.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 2 follows.
hole-block_a128_4_128-1_3.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

