// File version
11

// Number of components
4

// Component 0 follows.
shedleg1.leaf
// Translation x, y, z
16
0
15
// Rotation x, y, z
0
0
0

// Component 1 follows.
shedleg1.leaf
// Translation x, y, z
16
0
-15
// Rotation x, y, z
0
0
0

// Component 2 follows.
shedleg1.leaf
// Translation x, y, z
-15
0
-15
// Rotation x, y, z
0
0
0

// Component 3 follows.
shedleg1.leaf
// Translation x, y, z
-15
0
15
// Rotation x, y, z
0
0
0

