// File version
11

// Number of components
25

// Component 0 follows.
table2-bigpockets.comp
// Translation x, y, z
0.0765502
0.46058
-22.8463
// Rotation x, y, z
0
0
0

// Component 1 follows.
table3-bigpockets.comp
// Translation x, y, z
-15.4383
0.560682
2.36515
// Rotation x, y, z
0
0
0

// Component 2 follows.
table6-bigpockets.comp
// Translation x, y, z
-16.9806
-0.0320411
-25.3384
// Rotation x, y, z
0
0
0

// Component 3 follows.
table7-bigpockets.comp
// Translation x, y, z
-17.0433
0.0448184
0.125019
// Rotation x, y, z
0
0
0

// Component 4 follows.
table8.leaf
// Translation x, y, z
0
1
0
// Rotation x, y, z
0
0
0

// Component 5 follows.
table9.leaf
// Translation x, y, z
-8.67392
-4.77471
-15.9589
// Rotation x, y, z
0
0
0

// Component 6 follows.
table9.leaf
// Translation x, y, z
-8.6006
-4.83534
16.3545
// Rotation x, y, z
0
0
0

// Component 7 follows.
table9.leaf
// Translation x, y, z
8.6159
-4.66549
16.3545
// Rotation x, y, z
0
0
0

// Component 8 follows.
table9.leaf
// Translation x, y, z
8.7478
-4.73839
-15.9589
// Rotation x, y, z
0
0
0

// Component 9 follows.
table11.leaf
// Translation x, y, z
-0.165798
11.1018
8.99911
// Rotation x, y, z
0
0
0

// Component 10 follows.
table-r1-bigpockets.leaf
// Translation x, y, z
4.73772
0.400837
22.5175
// Rotation x, y, z
0
0
0

// Component 11 follows.
table-r2-bigpockets.leaf
// Translation x, y, z
11.8196
0.456114
6.51508
// Rotation x, y, z
0
0
0

// Component 12 follows.
baize-bigpockets.leaf
// Translation x, y, z
0.222335
10
0.310659
// Rotation x, y, z
0
0
0

// Component 13 follows.
table2-bigpockets.comp
// Translation x, y, z
-0.0664659
0.460579
23.2485
// Rotation x, y, z
0
180
0

// Component 14 follows.
table3-bigpockets.comp
// Translation x, y, z
-15.4792
0.460579
-19.9573
// Rotation x, y, z
0
0
0

// Component 15 follows.
table3-bigpockets.comp
// Translation x, y, z
15.4006
0.560682
-2.04251
// Rotation x, y, z
0
180
0

// Component 16 follows.
table3-bigpockets.comp
// Translation x, y, z
15.3862
0.460579
20.0909
// Rotation x, y, z
0
180
0

// Component 17 follows.
table6-bigpockets.comp
// Translation x, y, z
-36.1226
0
6.65767
// Rotation x, y, z
0
90
0

// Component 18 follows.
table6-bigpockets.comp
// Translation x, y, z
16.914
0
25.6686
// Rotation x, y, z
0
180
0

// Component 19 follows.
table6-bigpockets.comp
// Translation x, y, z
36.0758
0
-6.39638
// Rotation x, y, z
0
270
0

// Component 20 follows.
table7-bigpockets.comp
// Translation x, y, z
16.9329
0
0.105707
// Rotation x, y, z
0
180
0

// Component 21 follows.
table-r1-bigpockets.leaf
// Translation x, y, z
-4.66519
0.468732
-22
// Rotation x, y, z
0
180
0

// Component 22 follows.
table-r2-bigpockets.leaf
// Translation x, y, z
11.7069
0.506794
-15.2545
// Rotation x, y, z
0
0
0

// Component 23 follows.
table-r2-bigpockets.leaf
// Translation x, y, z
-11.8557
0.560517
-6.23466
// Rotation x, y, z
0
180
0

// Component 24 follows.
table-r2-bigpockets.leaf
// Translation x, y, z
-11.8029
0.560517
15.3723
// Rotation x, y, z
0
180
0

