// File version
11

// Number of components
25

// Component 0 follows.
table2-regular.comp
// Translation x, y, z
-0.0385031
0
-7.06816
// Rotation x, y, z
0
0
0

// Component 1 follows.
table3-regular.comp
// Translation x, y, z
-6.95999
0
1.28248
// Rotation x, y, z
0
0
0

// Component 2 follows.
table6-regular.comp
// Translation x, y, z
-8.12561
-0.49262
-8.81923
// Rotation x, y, z
0
0
0

// Component 3 follows.
table7-regular.comp
// Translation x, y, z
-8.14694
-0.50951
-0.0771777
// Rotation x, y, z
0
0
0

// Component 4 follows.
table8.leaf
// Translation x, y, z
0
1
0
// Rotation x, y, z
0
0
0

// Component 5 follows.
table9.leaf
// Translation x, y, z
-8.67392
-4.77471
-15.9589
// Rotation x, y, z
0
0
0

// Component 6 follows.
table9.leaf
// Translation x, y, z
-8.6006
-4.83534
16.3545
// Rotation x, y, z
0
0
0

// Component 7 follows.
table9.leaf
// Translation x, y, z
8.6159
-4.66549
16.3545
// Rotation x, y, z
0
0
0

// Component 8 follows.
table9.leaf
// Translation x, y, z
8.7478
-4.73839
-15.9589
// Rotation x, y, z
0
0
0

// Component 9 follows.
table11.leaf
// Translation x, y, z
-1
10.5637
14
// Rotation x, y, z
0
0
0

// Component 10 follows.
table-r1-crazy.leaf
// Translation x, y, z
6.06716
0
26.8677
// Rotation x, y, z
0
0
0

// Component 11 follows.
table-r2-crazy.leaf
// Translation x, y, z
13.3842
0
-19.6758
// Rotation x, y, z
0
180
0

// Component 12 follows.
table2-regular.comp
// Translation x, y, z
-0.0996537
0
6.95412
// Rotation x, y, z
0
180
0

// Component 13 follows.
table3-regular.comp
// Translation x, y, z
-6.90314
0
-26.1713
// Rotation x, y, z
0
0
0

// Component 14 follows.
table3-regular.comp
// Translation x, y, z
6.88861
0
-1.41447
// Rotation x, y, z
0
180
0

// Component 15 follows.
table3-regular.comp
// Translation x, y, z
6.94963
0
25.9512
// Rotation x, y, z
0
180
0

// Component 16 follows.
table6-regular.comp
// Translation x, y, z
-22.3766
-0.49262
-5.5391
// Rotation x, y, z
0
90
0

// Component 17 follows.
table6-regular.comp
// Translation x, y, z
7.8953
-0.49262
8.71179
// Rotation x, y, z
0
180
0

// Component 18 follows.
table6-regular.comp
// Translation x, y, z
22.2234
-0.49262
5.38374
// Rotation x, y, z
0
270
0

// Component 19 follows.
table7-regular.comp
// Translation x, y, z
7.99156
-0.49262
-0.0192516
// Rotation x, y, z
0
180
0

// Component 20 follows.
baize-regular-crazy.attr
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 21 follows.
table-r1-crazy.leaf
// Translation x, y, z
-6.25925
0
-26.9307
// Rotation x, y, z
0
180
0

// Component 22 follows.
table-r2-crazy.leaf
// Translation x, y, z
-13.4597
0
19.4517
// Rotation x, y, z
0
0
0

// Component 23 follows.
table-r2-crazy.leaf
// Translation x, y, z
13.3302
0
7
// Rotation x, y, z
0
180
0

// Component 24 follows.
table-r2-crazy.leaf
// Translation x, y, z
-13.3346
0
-7.07575
// Rotation x, y, z
0
0
0

