// File version
11

// Number of components
4

// Component 0 follows.
table7-1.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 1 follows.
table7-2.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

table7-3.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 2 follows.
table10.leaf
// Translation x, y, z
14.1423
10.1615
0.121688
// Rotation x, y, z
0
0
0

