// File version
11

// Number of components
4

// Component 0 follows.
table6-1-bigpockets.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 1 follows.
table6-2-bigpockets.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

table6-3-bigpockets.leaf
// Translation x, y, z
0
0
0
// Rotation x, y, z
0
0
0

// Component 2 follows.
table10-bigpockets.leaf
// Translation x, y, z
26.5984
10.2063
45.7806
// Rotation x, y, z
0
45
0

